var myContext = {
  myLocaldata: [
    {
      heading: 'jquery',
      image: 'img/big.jpg',
      category: 'jquery',
      address: 'https://en.wikipedia.org/wiki/JQuery',
      author: 'John Resig',
      paragraph: 'jQuery is a cross-platform JavaScript library designed to simplify the client-side scripting of HTML. jQuery is the most popular JavaScript library in use today, with installation on 65% of the top 10 million highest-trafficked sites on the Web. jQuery is free, open-source software licensed under the MIT License. jQuery\'s syntax is designed to make it easier to navigate a document, select DOM elements, create animations, handle events, and develop Ajax applications. jQuery also provides capabilities for developers to create plug-ins on top of the JavaScript library. This enables developers to create abstractions for low-level interaction and animation, advanced effects and high-level, themeable widgets. The modular approach to the jQuery library allows the creation of powerful dynamic web pages and Web applications.',
    },
    {
      heading: 'Handlebar',
      image: 'img/handlebars.jpg',
      category: 'Handlebar',
      address: 'http://tutorialzine.com/2015/01/learn-handlebars-in-10-minutes/',
      author:'Yehuda Katz',
      paragraph:'Handlebars.js is a popular templating engine that is powerful, simple to use and has a large community. It is based on the Mustache template language, but improves it in several important ways. With Handlebars, you can separate the generation of HTML from the rest of your JavaScript and write cleaner code. This quick article is an attempt to teach you almost everything you need to know about Handlebars in 10 minutes or less. It may seem a bit overwhelming in the beginning, but just like riding a bike (pun intended), after you get the hang of it, it becomes the easiest thing in the world. Checkout: <a href="http://handlebarsjs.com/">official site</a>',
    },
    {
      heading: 'SMACSS',
      image: 'img/smacss.png',
      category: 'css',
      address: 'https://smacss.com/',
      author:'Jonathan Snook',
      paragraph:'\"SMACSS (pronounced \"smacks\") is more style guide than rigid framework. There is no library within here for you to download or install. SMACSS is a way to examine your design process and as a way to fit those rigid frameworks into a flexible thought process. It is an attempt to document a consistent approach to site development when using CSS. And really, who isn’t building a site with CSS these days?!<a href="https://smacss.com/book/">Free Online Book</a>\: SMACSS started out as a free online book and that continues to be true. You can always read the original chapters.',
    },
    {
      heading: 'Crome Dev Tools',
      image: 'img/crome-dev.jpg',
      category: 'Tools',
      address: 'https://developer.chrome.com/home',
      author:'GoogleDev',
      paragraph:'The Chrome Developer Tools (DevTools for short), are a set of web authoring and debugging tools built into Google Chrome. The DevTools provide web developers deep access into the internals of the browser and their web application. Use the DevTools to efficiently track down layout issues, set JavaScript breakpoints, and get insights for code optimization. To access the DevTools, open a web page or web app in Google Chrome. Either: Select the Chrome menu at the top-right of your browser window, then select Tools > Developer Tools. Right-click on any page element and select Inspect Element.',
    },
    {
      heading: 'css-tricks',
      image: 'img/css.jpg',
      category: 'Tools',
      address: 'https://css-tricks.com/almanac/',
      author:'CSS',
      paragraph:'Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language. Although most often used to set the visual style of web pages and user interfaces written in HTML and XHTML, the language can be applied to any XML document, including plain XML, SVG and XUL, and is applicable to rendering in speech, or on other media. Along with HTML and JavaScript, CSS is a cornerstone technology used by most websites to create visually engaging webpages, user interfaces for web applications, and user interfaces for many mobile applications.',
    },
    {
      heading: 'CodePen',
      image: 'img/codePen.jpg',
      category: 'Tools',
      address: 'http://codepen.io/',
      author:'',
      paragraph:'',
    },
    // {
    //   heading: '',
    //   image: '',
    //   category: '',
    //   address: '',
    //   author:'',
    //   paragraph:'',
    // },
  ]
};
